version: '3.8'
services:
  mysql:
    container_name: mysql-sql-bsn
    image: mysql
    environment:
      MYSQL_DATABASE: Book
      MYSQL_ROOT_PASSWORD: anjusoni
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - spring-demo
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
#  app:
#    build: ./src/main/java
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
